### ISSUE TITLE
ajuda em material

### ISSUE THREAD

**Issue by RodrigoDornelles** [LelePG/rastreador-encomenda-correios#1]
Bom, existem algumas formas de API do correios bem pouco conhecidas, porque eles trabalham utilizando SOAP, mas acho que isso pode ajudar se precisar!

<https://www.correios.com.br/atendimento/ferramentas/sistemas/arquivos/web-service-de-rastreamento>

**Comment by LelePG** [comment]
Que legal, eu procurei por alguma coisa dos correios e não achei nada, só cheguei no rastrojs que é uma biblioteca pra node que já retorna todo o tracking do objeto dai vou usar ela por enquanto pra ir aprendendo um pouco sobre a parte do back da aplicação. Mas muito obrigada pelo material, vou ver se consigo fazer alguma coisa usando ele! :D
